
create table address
(
    id bigint generated by default as identity,
    street varchar(255),
    client_id int8,
    primary key (id)
);
create table phone
(
    id bigint generated by default as identity,
    number varchar(255),
    client_id int8,
    primary key (id)
);

alter table client
    add address_id bigint;

alter table address
    add constraint FK_address_client foreign key (client_id) references client (id);

alter table client
    add constraint FK_client_address foreign key (address_id) references address (id);

alter table phone
    add constraint fk_phone_client foreign key (client_id) references client (id);